/**
 * @file item17_item18.cpp
 * @brief EMC++条款17-18演示：特殊成员函数生成规则与unique_ptr资源管理
 * @author C++ Tutorial
 * @date Day 8
 * 
 * 条款17: 理解特殊成员函数的生成规则
 * 条款18: 使用unique_ptr管理独占资源
 */

#include <iostream>
#include <memory>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

// 辅助打印
#define LOG(msg) std::cout << "[LOG] " << msg << "\n"
#define LOG_NOEXCEPT(msg)                                                        \
    do {                                                                         \
        try {                                                                    \
            LOG(msg);                                                            \
        } catch (...) {                                                          \
        }                                                                        \
    } while (false)
#define SEP(title) std::cout << "\n======== " << title << " ========\n"

// ============================================================
// 条款17: 特殊成员函数生成规则演示
// ============================================================

/**
 * @brief 演示类：无任何显式声明
 * 
 * 编译器会自动生成所有特殊成员函数：
 * - 默认构造函数
 * - 析构函数
 * - 拷贝构造函数
 * - 拷贝赋值运算符
 * - 移动构造函数
 * - 移动赋值运算符
 */
class AutoGenerated {
    // 真正什么都不声明；是否可拷贝/移动仍取决于成员，这个空类的六项都可用。
};

/**
 * @brief 演示类：显式声明析构函数
 * 
 * 声明析构函数后：
 * - 移动操作不再自动生成
 * - 拷贝操作仍然自动生成（但已废弃的行为）
 */
class WithDestructor {
public:
    WithDestructor() : data_(new int(0)) {
        LOG_NOEXCEPT("WithDestructor 默认构造");
    }
    
    ~WithDestructor() {
        LOG_NOEXCEPT("WithDestructor 析构");
        delete data_;
    }

    // C++17仍会隐式声明拷贝，但裸指针会被浅拷贝并导致double-free。
    // 教学类型明确删除拷贝；这不改变上面的生成规则事实，而是安全的接口选择。
    WithDestructor(const WithDestructor&) = delete;
    WithDestructor& operator=(const WithDestructor&) = delete;
    // 移动操作不会被生成
    
private:
    int* data_;
};

/**
 * @brief 演示类：声明拷贝操作
 * 
 * 声明拷贝构造或拷贝赋值后：
 * - 移动操作不再自动生成
 */
class WithCopy {
public:
    WithCopy() : data_(new int(0)) { LOG_NOEXCEPT("WithCopy 默认构造"); }
    
    // 拷贝构造
    WithCopy(const WithCopy& other) : data_(new int(*other.data_)) {
        LOG_NOEXCEPT("WithCopy 拷贝构造");
    }
    
    // 拷贝赋值
    WithCopy& operator=(const WithCopy& other) {
        LOG("WithCopy 拷贝赋值");
        if (this != &other) {
            int* replacement = new int(*other.data_);
            delete data_;
            data_ = replacement;
        }
        return *this;
    }
    
    ~WithCopy() { delete data_; }
    
    // 移动操作不会自动生成
    
private:
    int* data_;
};

/**
 * @brief 演示类：声明移动操作
 * 
 * 声明移动操作后：
 * - 拷贝操作不再自动生成
 * - 默认构造函数不再自动生成
 */
class WithMove {
public:
    // 需要显式默认构造
    WithMove() : data_(new int(0)) { LOG_NOEXCEPT("WithMove 默认构造"); }
    
    // 移动构造
    WithMove(WithMove&& other) noexcept : data_(other.data_) {
        LOG_NOEXCEPT("WithMove 移动构造");
        other.data_ = nullptr;
    }
    
    // 移动赋值
    WithMove& operator=(WithMove&& other) noexcept {
        LOG_NOEXCEPT("WithMove 移动赋值");
        if (this != &other) {
            delete data_;
            data_ = other.data_;
            other.data_ = nullptr;
        }
        return *this;
    }
    
    ~WithMove() {
        LOG_NOEXCEPT("WithMove 析构");
        delete data_;
    }
    
    // 拷贝操作不会自动生成
    
private:
    int* data_;
};

/**
 * @brief Rule of Five 完整实现
 * 
 * 正确实现所有五个特殊成员函数
 */
class RuleOfFive {
public:
    // 1. 默认构造
    RuleOfFive() : data_(new int(0)) { LOG_NOEXCEPT("RuleOfFive 默认构造"); }
    
    // 2. 析构函数
    ~RuleOfFive() {
        LOG_NOEXCEPT("RuleOfFive 析构");
        delete data_;
    }
    
    // 3. 拷贝构造
    RuleOfFive(const RuleOfFive& other)
        : data_(other.data_ ? new int(*other.data_) : nullptr) {
        LOG_NOEXCEPT("RuleOfFive 拷贝构造");
    }
    
    // 4. 拷贝赋值
    RuleOfFive& operator=(const RuleOfFive& other) {
        LOG("RuleOfFive 拷贝赋值");
        if (this != &other) {
            int* newData = other.data_ ? new int(*other.data_) : nullptr;
            delete data_;
            data_ = newData;
        }
        return *this;
    }
    
    // 5. 移动构造
    RuleOfFive(RuleOfFive&& other) noexcept : data_(other.data_) {
        LOG_NOEXCEPT("RuleOfFive 移动构造");
        other.data_ = nullptr;
    }
    
    // 6. 移动赋值
    RuleOfFive& operator=(RuleOfFive&& other) noexcept {
        LOG_NOEXCEPT("RuleOfFive 移动赋值");
        if (this != &other) {
            delete data_;
            data_ = other.data_;
            other.data_ = nullptr;
        }
        return *this;
    }
    
    int value() const { return data_ ? *data_ : -1; }
    void setValue(int v) { if (data_) *data_ = v; }
    
private:
    int* data_;
};

/**
 * @brief Rule of Zero 最佳实践
 * 
 * 不声明特殊成员函数，让成员决定哪些操作可用
 */
class RuleOfZero {
public:
    explicit RuleOfZero(int value = 0) : data_(std::make_unique<int>(value)) {
        LOG("RuleOfZero 构造");
    }
    
    int value() const { return data_ ? *data_ : -1; }
    void setValue(int v) { if (data_) *data_ = v; }
    
    // 不需要声明任何特殊成员函数！
    // unique_ptr自动处理资源管理，因此本类自然可移动、不可拷贝
    
private:
    std::unique_ptr<int> data_;
};

class RuleOfZeroValue {
public:
    explicit RuleOfZeroValue(int value = 0) : data_(value) {}
    int value() const { return data_; }
private:
    int data_;
};

static_assert(std::is_default_constructible_v<AutoGenerated>);
static_assert(std::is_copy_constructible_v<AutoGenerated>);
static_assert(std::is_move_constructible_v<AutoGenerated>);
static_assert(!std::is_copy_constructible_v<WithMove>);
static_assert(std::is_nothrow_move_constructible_v<WithMove>);
static_assert(!std::is_copy_constructible_v<RuleOfZero>);
static_assert(std::is_nothrow_move_constructible_v<RuleOfZero>);
static_assert(std::is_copy_constructible_v<RuleOfZeroValue>);

// ============================================================
// 条款18: unique_ptr资源管理演示
// ============================================================

/**
 * @brief 投资基类
 */
class Investment {
public:
    virtual ~Investment() = default;
    virtual std::string name() const = 0;
    virtual double value() const = 0;
};

/**
 * @brief 股票投资
 */
class Stock : public Investment {
public:
    explicit Stock(const std::string& symbol, double price, int shares)
        : symbol_(symbol), price_(price), shares_(shares) {
        LOG("Stock 构造: " << symbol_);
    }
    
    ~Stock() override {
        LOG_NOEXCEPT("Stock 析构: " << symbol_);
    }
    
    std::string name() const override { return "Stock: " + symbol_; }
    double value() const override { return price_ * shares_; }
    
private:
    std::string symbol_;
    double price_;
    int shares_;
};

/**
 * @brief 债券投资
 */
class Bond : public Investment {
public:
    explicit Bond(const std::string& issuer, double faceValue)
        : issuer_(issuer), faceValue_(faceValue) {
        LOG("Bond 构造: " << issuer_);
    }
    
    ~Bond() override {
        LOG_NOEXCEPT("Bond 析构: " << issuer_);
    }
    
    std::string name() const override { return "Bond: " + issuer_; }
    double value() const override { return faceValue_; }
    
private:
    std::string issuer_;
    double faceValue_;
};

/**
 * @brief 投资类型枚举
 */
enum class InvestmentType { Stock, Bond };

/**
 * @brief 工厂函数：使用unique_ptr返回多态对象
 * 
 * 这是unique_ptr的经典应用场景：
 * - 返回指向基类的智能指针
 * - 自动管理派生类对象的生命周期
 * - 无需担心内存泄漏
 */
std::unique_ptr<Investment> makeInvestment(InvestmentType type) {
    switch (type) {
        case InvestmentType::Stock:
            return std::make_unique<Stock>("AAPL", 150.0, 100);
        case InvestmentType::Bond:
            return std::make_unique<Bond>("US Treasury", 10000.0);
    }
    return nullptr;
}

/**
 * @brief Pimpl惯用法演示
 * 
 * 使用unique_ptr隐藏实现细节
 */
// Widget.h 内容
class Widget {
public:
    Widget();
    explicit Widget(const std::string& name);
    ~Widget();  // 必须在实现文件中定义
    
    void doSomething();
    std::string name() const;
    
    // 拷贝操作需要自定义或删除（因为unique_ptr不可拷贝）
    Widget(const Widget&) = delete;
    Widget& operator=(const Widget&) = delete;
    
    // 移动操作可以显式默认
    Widget(Widget&&) noexcept = default;
    Widget& operator=(Widget&&) noexcept = default;
    
private:
    struct Impl;  // 前向声明
    std::unique_ptr<Impl> pImpl_;
};

// Widget.cpp 内容（在头文件中模拟）
struct Widget::Impl {
    std::string name;
    int value;
    
    Impl(const std::string& n) : name(n), value(42) {
        LOG("Widget::Impl 构造: " << name);
    }
    
    ~Impl() {
        LOG_NOEXCEPT("Widget::Impl 析构: " << name);
    }
};

Widget::Widget() : pImpl_(std::make_unique<Impl>("default")) {}
Widget::Widget(const std::string& name) : pImpl_(std::make_unique<Impl>(name)) {}
Widget::~Widget() = default;  // 必须在能看到Impl完整定义的地方定义

void Widget::doSomething() {
    std::cout << "Widget '" << pImpl_->name << "' doing something (value=" << pImpl_->value << ")\n";
}

std::string Widget::name() const { return pImpl_->name; }

/**
 * @brief 自定义删除器演示
 */
struct FileDeleter {
    void operator()(FILE* f) const noexcept {
        if (f) {
            LOG_NOEXCEPT("关闭文件");
            fclose(f);
        }
    }
};

using UniqueFile = std::unique_ptr<FILE, FileDeleter>;

// ============================================================
// 演示函数
// ============================================================

void demoItem17GenerationRules() {
    SEP("条款17: 特殊成员函数生成规则");
    
    std::cout << "\n【1. 自动生成所有函数的类】\n";
    AutoGenerated a1;
    AutoGenerated a2 = a1;   // 拷贝构造（隐式生成）
    AutoGenerated a3 = std::move(a1);  // 移动构造（隐式生成）
    (void)a2;
    (void)a3;
    
    std::cout << "\n【2. Rule of Five 完整实现】\n";
    RuleOfFive r1;
    r1.setValue(100);
    std::cout << "r1 value: " << r1.value() << "\n";
    
    RuleOfFive r2 = r1;  // 拷贝构造
    std::cout << "r2 (copy): " << r2.value() << "\n";
    
    RuleOfFive r3 = std::move(r1);  // 移动构造
    std::cout << "r3 (move): " << r3.value() << "\n";
    std::cout << "r1 after move: " << r1.value() << " (已转移)\n";
    
    std::cout << "\n【3. Rule of Zero 最佳实践】\n";
    RuleOfZero z1(200);
    std::cout << "z1 value: " << z1.value() << "\n";
    
    // RuleOfZero z2 = z1;  // 错误！unique_ptr不可拷贝
    RuleOfZero z2 = std::move(z1);  // OK
    std::cout << "z2 (move): " << z2.value() << "\n";
    std::cout << "z1 after move: " << z1.value() << " (nullptr)\n";

    RuleOfZeroValue value1(300);
    RuleOfZeroValue value2 = value1;
    std::cout << "值成员Rule of Zero可独立拷贝: " << value2.value() << "\n";
}

void demoItem18UniquePtr() {
    SEP("条款18: unique_ptr资源管理");
    
    std::cout << "\n【1. 工厂函数模式】\n";
    auto stock = makeInvestment(InvestmentType::Stock);
    auto bond = makeInvestment(InvestmentType::Bond);
    
    std::cout << stock->name() << ", value: " << stock->value() << "\n";
    std::cout << bond->name() << ", value: " << bond->value() << "\n";
    
    std::cout << "\n【2. 容器中的unique_ptr】\n";
    std::vector<std::unique_ptr<Investment>> portfolio;
    portfolio.push_back(makeInvestment(InvestmentType::Stock));
    portfolio.push_back(makeInvestment(InvestmentType::Bond));
    
    std::cout << "Portfolio:\n";
    for (const auto& inv : portfolio) {
        std::cout << "  - " << inv->name() << "\n";
    }
    
    std::cout << "\n【3. Pimpl惯用法】\n";
    Widget w1("Widget1");
    w1.doSomething();
    
    Widget w2 = std::move(w1);  // 移动构造
    std::cout << "w2 name: " << w2.name() << "\n";
    
    std::cout << "\n【4. 自定义删除器】\n";
    {
        UniqueFile file(fopen("/tmp/test_day8.txt", "w"));
        if (file) {
            fprintf(file.get(), "Hello, unique_ptr!\n");
            LOG("写入文件成功");
        }
        // 离开作用域，FileDeleter自动关闭文件
    }
    LOG("文件已自动关闭");
}

// ============================================================
// 主函数
// ============================================================

int main() {
    std::cout << "╔═════════════════════════════════════════════════════════════╗\n";
    std::cout << "║   EMC++条款17-18: 特殊成员函数与unique_ptr资源管理          ║\n";
    std::cout << "╚═════════════════════════════════════════════════════════════╝\n";
    
    demoItem17GenerationRules();
    demoItem18UniquePtr();
    
    SEP("总结");
    std::cout << "\n【条款17核心要点】\n";
    std::cout << "  1. 默认构造函数：只在没有任何构造函数时生成\n";
    std::cout << "  2. 析构函数：未声明时隐式生成；用户声明后采用用户版本\n";
    std::cout << "  3. C++17中用户析构不删除隐式拷贝，但该隐式拷贝已属弃用且常不安全\n";
    std::cout << "  4. 移动操作：仅在没有用户声明的拷贝、移动和析构时隐式生成\n";
    std::cout << "  5. Rule of Zero不保证都可拷贝；可用性取决于成员的语义\n";
    
    std::cout << "\n【条款18核心要点】\n";
    std::cout << "  1. unique_ptr是独占所有权资源管理的首选\n";
    std::cout << "  2. 默认无状态删除器下通常与原生指针同样轻量\n";
    std::cout << "  3. 适用于工厂函数、Pimpl惯用法\n";
    std::cout << "  4. 支持自定义删除器处理特殊资源\n";
    std::cout << "  5. 优先使用make_unique创建\n";
    
    return 0;
}
